print("a" in ["a", "b", "c", "d"])
print(9 in [3, 2, 9, 10, 9.0])
print('wow' not in ['gee wiz', 'gosh golly', 'wow', 'amazing'])
print("a" in ["apple", "absolutely", "application", "nope"])
print('ap' in 'apple')
